### ISSUE TITLE
unity中生成时丢失材质

### ISSUE THREAD

**Issue by SeanTongTx** [zhouzhanglin/DragonBone_Unity#2]
在 ShowArmature.ShowSkins里
if(meshSpriteCount==0 )
						{
							//can delete safely
							foreach(Material mat in matKV.Values){
								AssetDatabase.DeleteAsset( AssetDatabase.GetAssetPath(mat));
							}
						}

如果2个armature前一个使用meshSprite 后一个不使用时 会误删材质

**Comment by zhouzhanglin** [comment]
bug已经修复
