### ISSUE TITLE
unity中播放动画时候如果deactive/active导致动画错误

### ISSUE THREAD

**Issue by brucezhu99** [zhouzhanglin/DragonBone_Unity#3]
你好，非常感谢你能开发出这么方便的工具来导入dragonbone动画到unity，我们使用了一段时间感觉非常方便，不过最近发现了一个bug：使用目前最新版本的DragonBone_unity导入工具导入dragonbone动画到Unity后，生成sprite，sprite具有多个animation，在场景中播放其中一个animation时候，如果将sprite deactivate后（我们设置了个pool manager，当怪物被打死后回收到pool里面，用的是deactive的方法，打死后不播放死亡动画），再程序控制重新active它后，自动播放同deactivate时候不同的动画后，动画里面部件会错位，感觉像是里面部件的位置没有reset在重新active后？例如我们这个sprite有两个animation，一个是待机，一个是攻击动画，animator默认刚启动的是待机动画，待机动画有外部trigger触发会切换到攻击动画。当正在播放攻击的动画时候，判断怪物被打死，然后还没播放攻击动画完突然就deactivate，然后后面某个时刻spawn出来再activate，animator默认从待机动画开始播放，此时就会发生部件、角度的错位，很多部件感觉是保持了攻击时候的位置、角度没有重置。请问这是什么原因导致，有解决方案吗？
谢谢！

**Comment by zhouzhanglin** [comment]
试试在设置deactivate前把角色先设置成播放待机动画，然后才deactive

**Comment by brucezhu99** [comment]
你说的设置会造成动画不自然，请问有没有可能从目前dragonbone的代码上面来解决呢？

**Comment by zhouzhanglin** [comment]
怎么会不自然？就是在deactive之前加一行设置成默认动画的代码，应该不会影响到当前画面。或者 角色死亡的时候，先把角色移动到相机看不见的地方，再设置。这个bug暂时还不知道是什么引起的，也许还是unity的Animator的bug。

**Comment by zhouzhanglin** [comment]
这儿有一些相同的问题
https://forum.unity3d.com/threads/reset-animator-usage-with-pooled-object.290792/
http://answers.unity3d.com/questions/908981/problems-with-animator-when-disableenable-gameobje.html
